### ISSUE TITLE
I am getting the following exception while connecting to cassandra while passing credentials

### ISSUE THREAD

**Issue by vsonone** [cybem/cyanite-remover#1]
I am using the following command:
./cyanite-remover --threshold 172800 --log-level all --log-file /tmp/cyanite-remover.log --cassandra-options "{:credentials {user "user", password "password"}}" --elasticsearch-index cyanite_paths_20150914 --cassandra-keyspace metric --sort remove-obsolete-data "" 3600:6048000 carbon.cns.collectd._._ csHost http://esServer:9200

It appears that the user name and password is null in PlainTextAuthenticator, although I am providing it as part of cassandra-options. Can you please suggest what am I missing here ?

Following are the logs along with exception:
TRACE [2016-07-17 12:29:46,561] cluster1-nio-worker-0 - com.datastax.driver.core.Connection - Connection[sl73rtgpapd003/10.211.147.199:9042-1, inFlight=0, closed=false] request sent successfully
TRACE [2016-07-17 12:29:46,566] cluster1-nio-worker-0 - com.datastax.driver.core.Connection - Connection[sl73rtgpapd003/10.211.147.199:9042-1, inFlight=0, closed=false] received: AUTHENTICATE org.apache.cassandra.auth.PasswordAuthenticator
DEBUG [2016-07-17 12:29:46,571] cluster1-nio-worker-0 - com.datastax.driver.core.Connection - Defuncting connection to sl73rtgpapd003/10.211.147.199:9042
com.datastax.driver.core.ConnectionException: [sl73rtgpapd003/10.211.147.199:9042] Unexpected error during transport initialization (java.lang.NullPointerException)
        at com.datastax.driver.core.Connection$2.create(Connection.java:187)
        at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:468)
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1140)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:882)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:895)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
        at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1170)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1000)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:922)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.datastax.driver.core.PlainTextAuthProvider$PlainTextAuthenticator.<init>(PlainTextAuthProvider.java:73)
        at com.datastax.driver.core.PlainTextAuthProvider.newAuthenticator(PlainTextAuthProvider.java:59)
        at com.datastax.driver.core.Connection$5.apply(Connection.java:251)
        at com.datastax.driver.core.Connection$5.apply(Connection.java:238)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:859)
        ... 27 more

**Comment by kirillk77** [comment]
Hi @vsonone,

Sorry for the long wait. I think there is a error in the command line. You should use colons with options. So the correct value of the `cassandra-options` parameter looks like this: `"{:credentials {:user "user" :password "password"}}"`
